apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rd-app
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rd-app-api
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
