apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rd-app
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./infra/charts/rd-app
      version: "0.2.2"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    rdApp:
      api:
        image:
          tag: latest # {"$imagepolicy": "default:rd-api:tag"}
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgres-rw:5432/rd-capstone
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-app
                key: username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-app
                key: password
      ui:
        image:
          tag: latest # {"$imagepolicy": "default:rd-ui:tag"}
