apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rd-app
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./infra/charts/rd-app
      version: "0.1.1"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    rdApp:
      api:
        image:
          tag: latest # {"$imagepolicy": "default:rd-api:tag"}
      ui:
        image:
          tag: latest # {"$imagepolicy": "default:rd-ui:tag"}
