apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rd-app
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./infra/charts/rd-app
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: rd-app
        namespace: flux-system
