apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  bootstrap:
    initdb:
      database: rd-capstone
      owner: rd_user
      secret:
        name: rd-secret
  instances: 1
  storage:
    size: 1Gi
