apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rd-app
  namespace: flux-system
spec:
  interval: 5m
  values:
    rdApp:
      api:
        replicas: 1
        image:
          tag: dev # {"$imagepolicy": "flux-system:rd-api:tag"}
