apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rd-app
  namespace: flux-system
spec:
  interval: 5m
  values:
    rdApp:
      api:
        enabled: false
        replicas: 1
        image:
          tag: dev-20251216-141014 # {"$imagepolicy": "flux-system:rd-api:tag"}
      ui:
        replicas: 1
        image:
          tag: dev-20251216-143021 # {"$imagepolicy": "flux-system:rd-ui:tag"}
