apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pg-operator
  namespace: flux-system
spec:
  interval: 15m
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pg-operator
  namespace: flux-system
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.27.0
      sourceRef:
        kind: HelmRepository
        name: pg-operator
      interval: 5m
  releaseName: pg-operator
