apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 15m
  type: oci
  url: oci://quay.io/jetstack/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: cert-manager
      version: v1.19.2
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 10m
  releaseName: cert-manager
  values:
    crds:
      enabled: true
