apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rd-prod
  namespace: flux-system
spec:
  interval: 10m
  path: ./infra/apps/overlays/prod
  prune: true
  targetNamespace: prod
  sourceRef:
    kind: GitRepository
    name: prod
  dependsOn:
    - name: cert-manager
    - name: pg-operator
