apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rd-dev
  namespace: flux-system
spec:
  interval: 10m
  path: ./infra/app/overlays/dev
  prune: true
  targetNamespace: dev
  sourceRef:
    kind: GitRepository
    name: flux-system
