apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pg-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./infra/infrastructure/cnpg
  prune: true
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
