apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: prod
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/Avramenko-Vitaliy/rd-capstone.git
  ref:
    branch: prod
  secretRef:
    name: flux-system
