apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rd-app
  namespace: flux-system
spec:
  interval: 5m
  values:
    rdApp:
      api:
        enabled: false
        replicas: 3
        image:
          tag: prod
      ui:
        replicas: 1
        image:
          tag: prod
