apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rd-app
  namespace: flux-system
spec:
  interval: 5m
  values:
    rdApp:
      api:
        replicas: 3
        image:
          tag: prod # {"$imagepolicy": "prod:rd-api:tag"}
      ui:
        replicas: 3
        image:
          tag: prod # {"$imagepolicy": "prod:rd-ui:tag"}
