apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: rd-ui
  namespace: flux-system
spec:
  filterTags:
    pattern: '^prod-(?P<timestamp>.*)$'
    extract: '$timestamp'
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: rd-api
  namespace: flux-system
spec:
  filterTags:
    pattern: '^prod-(?P<timestamp>.*)$'
    extract: '$timestamp'
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: rd-automation
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: prod
    push:
      branch: prod
